spring:
  profiles.active: default
  datasource:
    url: jdbc:mysql://localhost/sport_planner
    username: rwagstaff
    password: therock8484
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    generate-ddl: true

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.hibernate: INFO

# Custom config
rest:
    proxy: true

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost/sport_planner
rest:
    proxy: false
---

spring:
  profiles: uat
  datasource:
    url: jdbc:mysql://localhost/sport_planner
rest:
    proxy: false

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/sport_planner
rest:
    proxy: false









